"""
MediTrace — Summary Export (PDF + TXT)
Doctor audience → full 6-section clinical PDF.
Patient audience → plain-language 2-section PDF.
Uses reportlab for PDF generation.
"""
from io import BytesIO
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


# ── PDF generation ─────────────────────────────────────────────────────────────

def _style(styles, name: str, **kw):
    s = styles["Normal"].clone(name)
    for k, v in kw.items():
        setattr(s, k, v)
    return s


def generate_pdf(patient: dict, summary: dict, audience: str = "doctor") -> bytes:
    """
    patient: {"first_name", "last_name", "patient_id"}
    summary: {"primary_conditions", "current_medications", ..., "model"}
    Returns raw PDF bytes.
    """
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet
        from reportlab.platypus import (
            SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        )
        from reportlab.lib import colors

        buf = BytesIO()
        doc = SimpleDocTemplate(
            buf, pagesize=A4,
            topMargin=48, bottomMargin=48,
            leftMargin=56, rightMargin=56,
        )

        styles = getSampleStyleSheet()
        title_s = _style(styles, "MT_Title",
                         fontSize=18, fontName="Helvetica-Bold",
                         textColor=colors.HexColor("#1352A2"), spaceAfter=4)
        meta_s  = _style(styles, "MT_Meta",
                         fontSize=9, textColor=colors.gray, spaceAfter=20)
        head_s  = _style(styles, "MT_Head",
                         fontSize=11, fontName="Helvetica-Bold",
                         textColor=colors.HexColor("#1A2B4A"),
                         spaceAfter=6, spaceBefore=14)
        body_s  = _style(styles, "MT_Body",
                         fontSize=10, leading=16, spaceAfter=4)
        foot_s  = _style(styles, "MT_Foot",
                         fontSize=8, textColor=colors.gray)

        story = []
        story.append(Paragraph("MediTrace — Clinical Summary", title_s))
        story.append(Paragraph(
            f"Patient: {patient.get('first_name','')} {patient.get('last_name','')}  |  "
            f"ID: {patient.get('patient_id','')}  |  "
            f"Generated: {datetime.now().strftime('%d %b %Y  %H:%M')}",
            meta_s,
        ))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor("#DDE8F5"), spaceAfter=12,
        ))

        if audience == "doctor":
            sections = {
                "Primary Conditions":   "primary_conditions",
                "Current Medications":  "current_medications",
                "Recent Trends":        "recent_trends",
                "Medication Adherence": "medication_adherence",
                "Risk Flags":           "risk_flags",
                "Overall Status":       "overall_status",
            }
        else:
            # Patient-friendly plain language version
            sections = {
                "Your Health Summary": "overall_status",
                "Your Medicines":      "current_medications",
            }

        for label, key in sections.items():
            content = summary.get(key, "").strip()
            if content and content.upper() != "NONE":
                story.append(Paragraph(label, head_s))
                story.append(Paragraph(content.replace("\n", " "), body_s))

        story.append(Spacer(1, 24))
        story.append(HRFlowable(
            width="100%", thickness=0.5,
            color=colors.HexColor("#DDE8F5"),
        ))
        story.append(Spacer(1, 8))
        model = summary.get("model", "AI")
        story.append(Paragraph(
            f"Generated by MediTrace · Powered by {model} · "
            f"AI-generated summary — clinical judgment required.",
            foot_s,
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        logger.error("[Export] reportlab not installed. Run: pip install reportlab")
        raise RuntimeError("reportlab is required. Install it with: pip install reportlab")


# ── TXT generation ─────────────────────────────────────────────────────────────

def generate_txt(patient: dict, summary: dict) -> str:
    lines = [
        "MEDITRACE — CLINICAL SUMMARY",
        "=" * 40,
        f"Patient : {patient.get('first_name','')} {patient.get('last_name','')}",
        f"ID      : {patient.get('patient_id','')}",
        f"Date    : {datetime.now().strftime('%d %b %Y %H:%M')}",
        f"Model   : {summary.get('model', '')}",
        "=" * 40,
        "",
    ]
    for key, label in [
        ("primary_conditions",   "PRIMARY CONDITIONS"),
        ("current_medications",  "CURRENT MEDICATIONS"),
        ("recent_trends",        "RECENT TRENDS"),
        ("medication_adherence", "MEDICATION ADHERENCE"),
        ("risk_flags",           "RISK FLAGS"),
        ("overall_status",       "OVERALL STATUS"),
    ]:
        val = summary.get(key, "").strip()
        if val and val.upper() != "NONE":
            lines += [label, "-" * len(label), val, ""]
    lines.append("AI-generated. Clinical judgment required.")
    return "\n".join(lines)
